config/routes.rb
Rails.application.routes.draw do
  root "entries#index"

  # Whenever we perform CRUD Operations on an item along with its controller and views, it is called a Resource
  # Run `rails routes` to view the different routes available 
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :weight, presence: true
    validates :highlight, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  # Implement the R in CRUD
  def show
    @entry = Entry.find(params[:id])
  end

  # The new action instantiates a new entry but does NOT save it
  def new 
    @entry = Entry.new
  end

  # Implement the C in CRUD using the new method 
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render :new, status: :unprocessable_entity
    end
  end

  # This action fetches the article from the database and stores it in @entry
  def edit
    @entry = Entry.find(params[:id])
  end

  # Implement the U in CRUD 
  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Implement the D in CRUD 
  
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def entry_params
      params.require(:entry).permit(:date, :highlight, :weight, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-4">
      <%= form_with model: entry, class: "mt-4" do |form| %>
        <div class="form-group mb-4">
          <%= form.label :date, class: "form-label" %>
          <%= form.date_field :date, class: "form-control" %>
        </div>

        <div class="form-group mb-4">
          <%= form.label :highlight, class: "form-label" %>
          <%= form.text_field :highlight, class: "form-control" %>
          <% entry.errors.full_messages_for(:highlight).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>

        <div class="form-group mb-4">
          <%= form.label :weight, class: "form-label" %>
          <%= form.number_field :weight, step: 0.1, class: "form-control" %>
          <% entry.errors.full_messages_for(:weight).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>

        <div class="form-group mb-4">
          <%= form.label :notes, class: "form-label" %>
          <%= form.text_area :notes, class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= form.submit "Submit", class: "btn btn-primary btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/edit.html.erb
<h1> Edit Entry </h1>

<%= render "form", entry: @entry %>

app/views/entries/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="mt-5 mb-4">Abhinav's Journal</h1>
      <h1 class="mt-5"><%= Date.today.strftime("%B %Y") %></h1>
      <h3 class="mt-4"><%= link_to "New Entry", new_entry_path, class: "btn btn-primary" %></h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Day</th>
            <th>Highlight</th>
            <th>Weight</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @entries.each do |entry| %>
            <tr>
              <td><%= entry.date.strftime("%d") %></td>
              <td><%= entry.highlight %></td>
              <td><%= entry.weight %></td>
              <td>
                <%= link_to "Edit", edit_entry_path(entry), class: "btn btn-primary btn-sm" %>
                <%= link_to "Delete", entry, method: :delete, data: { confirm: "Are you sure you want to delete this entry?" }, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 mt-5">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h5 class="card-title mb-0">New Entry</h5>
        </div>
        <div class="card-body">
          <%= render "form", entry: @entry %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.highlight %></h1>

<p><%= @entry.weight %></p>


<ul>
  <li><%= link_to "Edit", edit_entry_path(@entry) %></li>
  <li>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    </head>

  <body>
    <%= yield %>
  </body>
</html>